### ISSUE TITLE
Compatibility with Jest 28

### ISSUE THREAD

**Issue by ezzatron** [ambar/es-jest#3]
Hey there. Thanks for the module. I believe [a small change](https://jestjs.io/docs/upgrading-to-jest28#transformer) might be needed for Jest 28 compatibility, as I'm getting the current error:

```
 FAIL  test/jest/module-a.spec.js
  ● Test suite failed to run

    ● Invalid return value:
      `process()` or/and `processAsync()` method of code transformer found at
      "/Users/erin/grit/github.com/make-files/makefiles/test/pkg-js/npm/node_modules/es-jest/transform.js"
      should return an object or a Promise resolving to an object. The object
      must have `code` property with a string of processed code.
      This error may be caused by a breaking change in Jest 28:
      https://jestjs.io/docs/upgrading-to-jest28#transformer
      Code Transformation Documentation:
      https://jestjs.io/docs/code-transformation


      at ScriptTransformer._buildTransformResult (node_modules/@jest/transform/build/ScriptTransformer.js:507:15)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:628:17)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

**Comment by ambar** [comment]
@ezzatron Release v2.0, should be fixed.

**Comment by ezzatron** [comment]
Awesome, thanks!
